# Generated by Django 3.2.16 on 2023-05-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_post_evsahibi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='yildiz',
        ),
    ]
